BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Deliveries] (
    [id] INT NOT NULL IDENTITY(1,1),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Deliveries_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [username] VARCHAR(255) NOT NULL,
    CONSTRAINT [Deliveries_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
