BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[deliveries] ALTER COLUMN [final_latitude] FLOAT(53) NULL;
ALTER TABLE [dbo].[deliveries] ALTER COLUMN [final_longitude] FLOAT(53) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
